### ISSUE TITLE
ProjectEdit throw an "InvalidOperationException"

### ISSUE THREAD

**Issue by selway** [ProgTrade/nUpdate#48]
Version: 3.2.1
ProjectEditDialog.cs
![image](https://user-images.githubusercontent.com/6679547/37132691-0c75cf64-22ca-11e8-93ee-3ea1d02073b5.png)
![image](https://user-images.githubusercontent.com/6679547/37132704-22af0a20-22ca-11e8-9fba-532f8e8ff095.png)
The exception message means "Cross-thread operation not valid: Control ‘ProjectEditDialog’ accessed from a thread other than the thread it was created on".

**Comment by ProgTrade** [comment]
Hi,

could you please give me the exact lines and code files where the error appears?
Or maybe a complete StackTrace in English?

Best,
Dominic

**Comment by selway** [comment]
The StackTrace
`
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.GetSafeHandle(IWin32Window window)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at nUpdate.Administration.UI.Popups.Popup.ShowPopup(IWin32Window owner, Icon popupIcon, String title, String infoMessage, PopupButtons buttons) 
   in E:\Projects\nUpdate_fork\nUpdate.Administration\UI\Popups\Popup.cs:line 74
   at nUpdate.Administration.UI.Dialogs.ProjectEditDialog.<InitializeData>b__66_0() 
   in E:\Projects\nUpdate_fork\nUpdate.Administration\UI\Dialogs\ProjectEditDialog.cs:line 997
   at System.Threading.Tasks.Task.Execute()
`

**Comment by ProgTrade** [comment]
Thank you very much! I will check that out.
